### ISSUE TITLE
CHECK_EQ with enum values

### ISSUE THREAD

**Issue by killkrt** [onqtam/doctest#276] opened 2019-08-21 14:41 UTC
## Description
I don't know if it could be a bug or it is more a feature request.
Anyway if you compare two enum values using `CHECK_EQ` and the check fails, the error message shows question mark instead of values.

I would expect that the enum values are casted to integer by default. Or maybe to  have a macro (e.g.: `CHECK_EQ_ENUM`) that automatically cast to int.

## Extra info
* doctest version: 2.3.3
* Operating System: Arch Linux x86_64 5.2.9
* Compiler+version: clang 8.0.1

**Comment by onqtam** [comment] 2019-08-21 21:00
This is a duplicate of this: https://github.com/onqtam/doctest/issues/121

**Comment by Trass3r** [comment] 2020-07-28 14:47
Yes looks like a duplicate.

**Comment by onqtam** [comment] 2020-11-07 11:37
closing this one since #121 has been implemented & closed

**Closed by onqtam** 2020-11-07 11:37 UTC
