### ISSUE TITLE
Warnings when using something more than /W4 for Visual Studio

### ISSUE THREAD

**Issue by Leandros** [onqtam/doctest#95] opened 2017-10-19 20:41 UTC
There is a bug in the switch in `getAssertString`, it's not handling all cases:

```
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_throws' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_throws_as' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_nothrow' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_fast' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_false' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_unary' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_eq' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_ne' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_lt' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_gt' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_ge' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'
c:\<redacted>\tests\doctest.h(3854,9): error C4062: enumerator 'doctest::detail::assertType::is_le' in switch of enum 'doctest::detail::assertType::Enum' is not handled
c:\<redacted>\tests\doctest.h(1018): note: see declaration of 'doctest::detail::assertType::Enum'

```

**Comment by onqtam** [comment] 2017-10-20 19:51
Hi!

It's not a bug - see [here](https://github.com/onqtam/doctest/blob/master/doctest/doctest.h#L1042) - the first N values of the enum are used later (with bitwise OR) to define the assert types.

So OCLint is reporting this for you? You might suppress errors from the header in some way. I also use OCLing on the CI (travis) - see [here](https://github.com/onqtam/doctest/blob/master/.travis.yml#L409) - but I suppress some things (after I've reviewed each case that the static analyzer reported)

**Comment by Leandros** [comment] 2017-10-20 21:46
MSVC is reporting this, since I'm compiling with warnings enabled & treated as error.

**Comment by onqtam** [comment] 2017-10-24 07:42
Oh I see... that warning is a level 4 (and doctest is built with ```/W4``` on multiple versions of VS) but is off by default... see [here](https://msdn.microsoft.com/en-us/library/23k5d385.aspx) - I'll fix this in a few days/weeks - thanks for reporting!

**Comment by onqtam** [comment] 2017-10-28 18:31
This should be fixed in the dev branch - will end up in master very soon!

**Closed** 2017-10-29 14:09 UTC
