### ISSUE TITLE
Compile failure with WinRT on 2.4.5

### ISSUE THREAD

**Issue by bnason-nf** [onqtam/doctest#465] opened 2021-02-04 06:45 UTC
Hi,

I just updated to version 2.4.5, and the Windows UWP build using doctest gets this compile error:

```
doctest\doctest/doctest.h(3070,41): error C2482: 'tlsLaneIdx': dynamic initialization of thread local data not allowed in WinRT code
doctest\doctest/doctest.h(3068): message : while compiling class template member function 'std::atomic<int> &doctest::detail::MultiLaneAtomic<int>::myAtomic(void) noexcept'
doctest\doctest/doctest.h(3025): message : see reference to function template instantiation 'std::atomic<int> &doctest::detail::MultiLaneAtomic<int>::myAtomic(void) noexcept' being compiled
doctest\doctest/doctest.h(3084): message : see reference to class template instantiation 'doctest::detail::MultiLaneAtomic<int>' being compiled
```
This error is documented here:
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2482

It's trivial to avoid the error by splitting the declaration and the assignment, but I'm not sure this code is doing what you intend since the variable isn't static, or maybe I'm misunderstanding.

Thanks,
Benbuck

**Comment by onqtam** [comment] 2021-02-04 13:27
Hi,

`thread_local` implies `static` when used in function-scope so that code should be fine.

Regarding your problem - the documentation you link to states that `A static expression is required to initialize __declspec(thread) or thread_local data in these runtime environments.` so I guess the problem is that `laneCounter++ % DOCTEST_MULTI_LANE_ATOMICS_THREAD_LANES` is not a static expression and that's not permitted in that environment. 

What you could do is simply define `DOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS` before including the framework header (`#define DOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS` and then `#include <doctest.h>`).

Let me know if that helps :)

**Comment by bnason-nf** [comment] 2021-02-04 18:39
Hi Viktor,

Defining DOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS does avoid the problem. I'm not sure what the actual solution would be if you wanted to support that feature under WinRT, but the workaround is sufficient for my needs.

Thanks,
Benbuck

**Comment by onqtam** [comment] 2021-02-18 09:05
Seems that other people are having problems with this as well: https://github.com/jupyter-xeus/cpp-terminal/issues/88

Assuming there is a macro to detect WinRT (something like `__cplusplus_winrt` or anything mentioned [here](https://stackoverflow.com/questions/11961771/macro-to-recognize-winrt)) it should be possible to simply add
```c++
#ifdef WINRT
#define DOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS
#endif
```

**Comment by bnason-nf** [comment] 2021-02-22 18:54
Hi @onqtam,

This seems to be the right way to do the ifdef:

```
#if defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_APP)
#define DOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS
#endif
```

Would that be something you would be willing to add into doctest itself?

Thanks,
Benbuck

**Comment by onqtam** [comment] 2021-03-21 12:19
Thanks! fixed in the `dev` branch

**Closed by onqtam** 2021-03-21 12:19 UTC
