### ISSUE TITLE
SUPER_FAST_ASSERTS fails to compile CHECK_MESSAGE

### ISSUE THREAD

**Issue by tbsmark86** [onqtam/doctest#281] opened 2019-08-28 18:46 UTC
Version: 2.3.4
It was ok in Version 1.2.9

This does not compile:

      #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
      #define DOCTEST_CONFIG_SUPER_FAST_ASSERTS
      #include "doctest/doctest.h"

       TEST_CASE("simple")
       {
              CHECK_MESSAGE(true == false, "strange");
       }

However when I remove the SUPER_FAST_ASSERTS it does.

Error:
test.c: In function ‘void _DOCTEST_ANON_FUNC_6()’:
doctest/doctest.h:2063:93: error: ‘DT_CHECK’ was not declared in this scope
In file included from test.c:5:0:
doctest/doctest.h:2063:66: error: ‘DOCTEST_ASSERT_IMPLEMENT_2’ was not declared in this scope

I was able to workaround this by simply duplicating the 
     DOCTEST_ASSERT_IMPLEMENT_1 macro as  "_2"

**Comment by onqtam** [comment] 2019-08-28 19:49
This is a duplicate of this issue: https://github.com/onqtam/doctest/issues/280

It's fixed in the dev branch and will be made available in the master branch once I release a new official version - not sure when that is happening though... :)

**Comment by onqtam** [comment] 2019-09-22 18:19
releasing 2.3.5 where this is fixed.

**Closed** 2019-09-22 18:18 UTC
