### ISSUE TITLE
doctest + SDL2main :  error LNK2019 (despite using DOCTEST_CONFIG_IMPLEMENT)

### ISSUE THREAD

**Issue by corentin35000** [onqtam/doctest#860] opened 2024-06-24 09:03 UTC
I have the impression that despite using DOCTEST_CONFIG_IMPLEMENT, I have the impression that it redefines the main! I have this on Windows, while on Android I don't need the SDL2main link and I have no problems! I have the impression that doctest and SDL2main are in conflict! <br />

Error : SDL2main.lib(SDL_windows_main.obj) : error LNK2019: symbole externe non résolu _SDL_main référencé dans la fonction _main_getcmdline <br />

main.cpp : 

```c++
#include "game.h"
#include "unit-tests/unit-tests.h"
#include <rc2d/RC2D.h>

int main(int argc, char* argv[])
{
#ifdef NDEBUG // If we are in Release mode
    // Garder uniquement les logs critiques + Redirige la sortie dans un fichier
    rc2d_log_set_priority(RC2D_LOG_ERROR);
#else // If we are in Debug mode
    // Afficher tous les niveaux de logs
    rc2d_log_set_priority(RC2D_LOG_DEBUG);
#endif

#ifndef DOCTEST_CONFIG_DISABLE
    // Run all unit tests if Doctest is enabled
    // If tests fail, exit with error code
    if (rc2d_tests_runAllTests(argc, argv) != 0) return -1;
#endif

    RC2D_Callbacks myGameCallbacks = {};
    myGameCallbacks.rc2d_unload = rc2d_unload;
    myGameCallbacks.rc2d_load = rc2d_load;
    myGameCallbacks.rc2d_update = rc2d_update;
    myGameCallbacks.rc2d_draw = rc2d_draw;
    myGameCallbacks.rc2d_keypressed = rc2d_keypressed;
    myGameCallbacks.rc2d_keyreleased = rc2d_keyreleased;
    myGameCallbacks.rc2d_mousemoved = rc2d_mousemoved;
    myGameCallbacks.rc2d_mousepressed = rc2d_mousepressed;
    myGameCallbacks.rc2d_mousereleased = rc2d_mousereleased;
    myGameCallbacks.rc2d_wheelmoved = rc2d_wheelmoved;
    myGameCallbacks.rc2d_gamepadpressed = rc2d_gamepadpressed;
    myGameCallbacks.rc2d_gamepadreleased = rc2d_gamepadreleased;
    myGameCallbacks.rc2d_joystickpressed = rc2d_joystickpressed;
    myGameCallbacks.rc2d_joystickreleased = rc2d_joystickreleased;
    myGameCallbacks.rc2d_joystickadded = rc2d_joystickadded;
    myGameCallbacks.rc2d_joystickremoved = rc2d_joystickremoved;
    myGameCallbacks.rc2d_dropfile = rc2d_dropfile;
    myGameCallbacks.rc2d_droptext = rc2d_droptext;
    myGameCallbacks.rc2d_dropbegin = rc2d_dropbegin;
    myGameCallbacks.rc2d_dropcomplete = rc2d_dropcomplete;

    return rc2d_run(&myGameCallbacks, 1280, 720, 1280, 720, RC2D_RENDER_LOGICAL_SIZE_MODE_LETTERBOX, NULL);
}
```

and unit-tests.cpp : 

```c++
#include "unit-tests/unit-tests.h"
#define DOCTEST_CONFIG_IMPLEMENT // Il faut l'inclure que dans un seul fichier source et avant l'inclusion de doctest.h
#include <doctest/doctest.h>

// Run all tests with Doctest and return the result
int rc2d_tests_runAllTests(int argc, char* argv[])
{
    doctest::Context context;             // Initialisez le contexte
    context.applyCommandLine(argc, argv); // Appliquez les arguments de la ligne de commande
    int test_result = context.run();      // Executez les tests

    if(context.shouldExit() || test_result != 0) 
    {
        return test_result; // Termine l'exécution si Doctest demande de quitter ou si les tests échouent
    }

    return 0;
}

TEST_CASE("Example test case") {
    int x = 1;
    CHECK(x == 1); // Test success
    //CHECK(x == 2); // Test error
}
```

**Comment by mitchgrout** [comment] 2024-06-26 01:54
I think you're having issues with your `main` defined in `main.cpp` conflicting with the `main` which is bundled with SDL2. Try globally defining `SDL_MAIN_HANDLED` and see if linking succeeds. I'd also recommend setting up a minimal reproduction (including build configuration) to help figure out if the problem is with doctest itself

**Comment by cdeln** [comment] 2024-08-15 14:45
This is not a doctest bug.

Closing due to lack of information, non-reproducibility, non-engagement from OP after receiving suggested fix.

**Closed as not planned** 2024-08-15 14:45 UTC
Labels: verdict/false-positive
