### ISSUE TITLE
Support conditional expressions in REQUIRE

### ISSUE THREAD

**Issue by rherrmannr** [onqtam/doctest#262] opened 2019-08-02 15:03 UTC
## Description
Conditional expression seems not be supported for ``REQUIRE(..)`` and ``REQUIRE_FALSE(..)``.

A simple example:
```
void fn(bool cond) {
	REQUIRE(cond ? true : false);
}

TEST_CASE("test") {
	fn(true);
}
```

Compiler output:
```
../Test.cpp: In function ‘void guardedexit::fn(bool)’:
../doctest.h:2101:13: error: could not convert ‘doctest::detail::ExpressionDecomposer((doctest::assertType::Enum)12).doctest::detail::ExpressionDecomposer::operator<< <bool>(cond)’ from ‘doctest::detail::Expression_lhs<const bool&>’ to ‘bool’
             << __VA_ARGS__))                                                                       \
../doctest.h:1868:9: note: in definition of macro ‘DOCTEST_WRAP_IN_TRY’
         x;                                                                                         \
         ^
../doctest.h:2107:9: note: in expansion of macro ‘DOCTEST_ASSERT_IMPLEMENT_2’
         DOCTEST_ASSERT_IMPLEMENT_2(assert_type, __VA_ARGS__);                                      \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../doctest.h:2123:30: note: in expansion of macro ‘DOCTEST_ASSERT_IMPLEMENT_1’
 #define DOCTEST_REQUIRE(...) DOCTEST_ASSERT_IMPLEMENT_1(DT_REQUIRE, __VA_ARGS__)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
../doctest.h:2569:17: note: in expansion of macro ‘DOCTEST_REQUIRE’
 #define REQUIRE DOCTEST_REQUIRE
                 ^~~~~~~~~~~~~~~
../Test.cpp:46:2: note: in expansion of macro ‘REQUIRE’
  REQUIRE(cond ? true : false);
  ^~~~~~~
subdir.mk:21: recipe for target 'Test.o' failed
make: *** [Test.o] Error 1
```

Is it possible to add support for conditional expressions? 

### Extra information

* doctest version: **latest (2.3.3)** and **tag 1.2.9**
* Operating System: **Ubuntu 18.04.1**
* Compiler+version: **gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)**

**Comment by onqtam** [comment] 2019-08-05 11:55
You will need to wrap the expression in extra round braces (```REQUIRE((cond ? true : false))```) to make that work. The issue is that doctest uses a bunch of templates to decompose expressions so it is able to extract the left and right hand side of comparisons such as ```a == b```.

I'll keep this issue open just to investigate if there is anything that could be done in the future, but I might close it at some point.

**Comment by rherrmannr** [comment] 2019-08-05 12:07
Thanks for the fast response. This is very helpful for me :+1:

**Comment by onqtam** [comment] 2019-08-12 19:17
I thought about it a bit more and it's unlikely that there is anything that can be done on the side of doctest for this one. I'm closing it...

**Closed by onqtam** 2019-08-12 19:17 UTC
