### ISSUE TITLE
Build fails with gcc9 because of -Wstrict-overflow=5 which is too high

### ISSUE THREAD

**Issue by luigino** [onqtam/doctest#241] opened 2019-05-31 06:46 UTC
Trying to build 2.3.2 on openSUSE Tumbleweed, see [log](https://github.com/onqtam/doctest/files/3240053/doctest.txt).

**Comment by onqtam** [comment] 2019-06-01 17:57
doctest is built with GCC 9 on Travis CI with no errors. I suppose that on openSUSE the version of gcc 9 might be a tiny bit different. This warning (turned into an error) is not at all important - it is the result of [```-Wstrict-overflow=5```](https://github.com/onqtam/doctest/blob/master/scripts/cmake/common.cmake#L93) which is a total overkill (the level 5 - really easy to "break"). On this high level most reports are not real bugs but just a diagnostic.

I've had such errors previously with specific versions of GCC - notice that it reports the errors on line 51 of main.cpp - that is the last line of the source file. The reason this happens is because something gets inlined from the header into the source file and only then is the warning triggered - so this happens only in Release mode.

I cannot reproduce this with my local GCC 9 - I bet it's version is a bit different from yours. Here is what we can do:
- you could just trust me that this is not an important error and just use the doctest header
- I could somehow figure out which function gets inlined in the .cpp and mark it as "noinline" so it stays within the header where this warning is silenced
- I could reduce the level of the warning since 5 is impractical and just wastes our time

**Comment by luigino** [comment] 2019-06-02 08:34
No biggie, I will simply fall back on gcc8 for the time being.

**Comment by onqtam** [comment] 2019-06-02 11:41
forget about me saying that GCC 9 builds were passing - they were not: https://travis-ci.org/onqtam/doctest/jobs/538141168

it was in the allowed failures part of the Travis CI build matrix because gcc 9 wasn't available until recently. Anyway I just committed some stuff and will wait for the builds when I push the changes.

**Closed** 2019-06-02 14:43 UTC
